title: Anoosha Tariq
logo: /assets/img/logo.png
name: Anoosha Tariq
site_title: Anoosha Tariq
description: Hi, Welcome to my profile.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: "/Anoosha-Portfolio-2025"
url: "https://anoosha-tariq.github.io"
github:
  is_user_page: true
  owner_url: https://github.com/anoosha-tariq
  repository_url: https://github.com/anoosha-tariq/Anoosha-Portfolio-2025
  repository_nwo: anoosha-tariq/Anoosha-Portfolio-2025
linkedin_url: https://www.linkedin.com/in/anoosha-tariq-sahi
