title: Anoosha Tariq
logo: /assets/img/logo.png
name: Anoosha Tariq
site_title: Anoosha Tariq
description: Connect with me on LinkedIn!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# github:
#   is_user_page: true
#   owner_url: https://github.com/zanjeel
#   repository_url: https://github.com/zanjeel
#   repository_nwo: zanjeel
